// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: types.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MBotServerClient is the client API for MBotServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MBotServerClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerReply, error)
}

type mBotServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMBotServerClient(cc grpc.ClientConnInterface) MBotServerClient {
	return &mBotServerClient{cc}
}

func (c *mBotServerClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerReply, error) {
	out := new(CreateCustomerReply)
	err := c.cc.Invoke(ctx, "/MBotServer/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MBotServerServer is the server API for MBotServer service.
// All implementations must embed UnimplementedMBotServerServer
// for forward compatibility
type MBotServerServer interface {
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerReply, error)
	mustEmbedUnimplementedMBotServerServer()
}

// UnimplementedMBotServerServer must be embedded to have forward compatible implementations.
type UnimplementedMBotServerServer struct {
}

func (UnimplementedMBotServerServer) CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedMBotServerServer) mustEmbedUnimplementedMBotServerServer() {}

// UnsafeMBotServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MBotServerServer will
// result in compilation errors.
type UnsafeMBotServerServer interface {
	mustEmbedUnimplementedMBotServerServer()
}

func RegisterMBotServerServer(s grpc.ServiceRegistrar, srv MBotServerServer) {
	s.RegisterService(&MBotServer_ServiceDesc, srv)
}

func _MBotServer_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MBotServerServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MBotServer/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MBotServerServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MBotServer_ServiceDesc is the grpc.ServiceDesc for MBotServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MBotServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MBotServer",
	HandlerType: (*MBotServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _MBotServer_CreateCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
